package hu.bugbusters.corpus.core.vaadin.view.teacher.settings;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TeacherSettingsDesign extends VerticalLayout {
	protected Panel panel;
	protected TextField currentPassword;
	protected TextField newPaswsord1;
	protected TextField newPassword2;
	protected Button saveButton;
	protected Button cancelButton;

	public TeacherSettingsDesign() {
		Design.read(this);
	}
}
