package hu.bugbusters.corpus.core.vaadin.view.admin.homepage;

import com.askvikrant.digitalclock.DigitalClock;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AdminHomepageDesign extends VerticalLayout {
	protected Label lblWelcome;
	protected DigitalClock clock;

	public AdminHomepageDesign() {
		Design.read(this);
	}
}
